name: phone_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  location: ^5.0.3
  flutter_polyline_points: ^2.0.0
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  cupertino_icons: ^1.0.2
  awesome_dialog: ^3.0.2
  cloud_firestore: ^4.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
